sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
version:
  fromSource: pom.xml
build:
  freeDiskSpace: false
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        # Configure Snowflake credentials
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Snowflake credentials
            id: configure-snowflake-credentials
            run: |
              cat > test.properties <<EOL
              snowflake.username = ${{ secrets.USERNAME }}
              snowflake.accountname = ${{ secrets.ACCOUNTNAME }}
              snowflake.password = ${{ secrets.PASSWORD }}
              EOL
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: release.yml
      stepCustomizations:
        # Configure Snowflake credentials
        - action: INSERT_AFTER
          stepId: verify-release
          content:
            name: Configure Snowflake credentials
            id: configure-snowflake-credentials
            run: |
              cat > test.properties <<EOL
              snowflake.username = ${{ secrets.USERNAME }}
              snowflake.accountname = ${{ secrets.ACCOUNTNAME }}
              snowflake.password = ${{ secrets.PASSWORD }}
              EOL
