sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.25"
    - "8.24.0"  
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        # Configure Snowflake credentials
        - action: INSERT_AFTER
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Snowflake credentials
            id: configure-snowflake-credentials
            run: |
              echo "$USERNAME" > username.txt
              echo "$ACCOUNTNAME" > accountname.txt
              echo "$PASSWORD" > password.txt
            env: {
              USERNAME: '${{ secrets.USERNAME }}',
              ACCOUNTNAME: '${{ secrets.ACCOUNTNAME }}',
              PASSWORD: '${{ secrets.PASSWORD }}'
            }
    - name: release.yml
      stepCustomizations:
        # Configure Snowflake credentials
        - action: INSERT_AFTER
          stepId: verify-release
          content:
            name: Configure Snowflake credentials
            id: configure-snowflake-credentials
            run: |
              echo "$USERNAME" > username.txt
              echo "$ACCOUNTNAME" > accountname.txt
              echo "$PASSWORD" > password.txt
            env: {
              USERNAME: '${{ secrets.USERNAME }}',
              ACCOUNTNAME: '${{ secrets.ACCOUNTNAME }}',
              PASSWORD: '${{ secrets.PASSWORD }}'
            }