package com.exasol.adapter.dialects.snowflake.docgeneration;

import com.exasol.adapter.dialects.snowflake.SnowflakeSqlDialectFactory;
import com.exasol.autogeneratedresourceverifier.AutogeneratedResourceVerifier;

public class SnowflakeAutogeneratedResourceVerifier {

    public static void main(final String[] args) {
        new AutogeneratedResourceVerifier().verifyResource(new CapabilitiesReport(new SnowflakeSqlDialectFactory()));
    }
}
